var datasource_2003 = {
	"de": [
		{"year": "2003", "category": "Game Design", "shortcat": "de", "title": "Sequels and Adaptations: Design Innovation in a Risk-Averse World", "media": "video", "vid": "1014859", "vpage": "https://www.gdcvault.com/play/1014859", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc03/video/2003-spector-design-innovation.flv", "speaker": "Warren Spector", "company": "Ion Storm", "overview": ""},
		{"year": "2003", "category": "Game Design", "shortcat": "de", "title": "Halo: Development Evolved", "media": "video", "vid": "1016535", "vpage": "https://www.gdcvault.com/play/1016535", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc03/video/2003-gdc-halo-development-evolved_1.flv", "speaker": "Jaime Griesemer, Mat Noguchi, Marty O'Donnell", "company": "Bungie, , Bungie", "overview": ""},
		{"year": "2003", "category": "Game Design", "shortcat": "de", "title": "Dynamics for Designers", "media": "video", "vid": "1019938", "vpage": "https://www.gdcvault.com/play/1019938", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc03/video/2003-GDC-Dynamics-for-Designers-Will-Wright.flv", "speaker": "Will Wright", "company": "Stupid Fun Club", "overview": "Somewhere between high-level game concepts and low-level coding lies a region of design that's really at the core of the interactive medium. In this part of the forest we find that causal relationships, feedback cycles, information propagation, and emergence mechanisms reign supreme. This is what I call dynamics, the rules and principles that govern the way in which structures change through time. A new language is emerging here, and we are just now getting to the point where we can really use it to increase our effectiveness as designers. I hope to show how we can develop an intuitive \"feel\" for these dynamics and use them not as a recipe for design, but rather as a spice. The design and use of early prototypes will be covered as a means to explore and sculpt a variety of dynamic systems. Also, the use of dynamic literacy as a middle ground or \"shared language\" between programmers and designers will be emphasized."},
		{"year": "2003", "category": "Game Design", "shortcat": "de", "title": "Great Game Graphics... Who Cares?", "media": "video", "vid": "1016690", "vpage": "https://www.gdcvault.com/play/1016690", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc03/video/2003-rubin-great-game-graphics_1.flv", "speaker": "Jason Rubin", "company": "Naughty Dog", "overview": "Naughty Dog's co-founder discusses how graphics alone fail to impress and lead to profits as in previous console generations. Instead, he suggests a focus on innovation and licenses or sequels for games to thrive."}
	],
	"pg": [
		{"year": "2003", "category": "Programming", "shortcat": "pg", "title": "Little to Big: What Changes?", "media": "video", "vid": "1016691", "vpage": "https://www.gdcvault.com/play/1016691", "vdownload": "https://ubm-twvideo01.s3.amazonaws.com/o1/vault/gdc03/video/2003-gdc-fred-books-little-to-big_1.flv", "speaker": "Frederick Brooks, Jr.", "company": "", "overview": "This programming keynote focuses on issues in keeping productivity high while not stifling creativity with larger teams. Pair programming, having a producer and director, and several allowances for testing are a few suggestions for improvement."}
	]
}